import glob
from skimage.io import imread
import matplotlib.pylab as plt

i = 1
plt.figure(figsize=(15,20))
plt.gray()
plt.subplots_adjust(left=0, right=1, bottom=0, top=0.9, wspace=0.05, hspace=0.1)
for imfile in glob.glob('sample*.png'):
	print(imfile)
	plt.subplot(5,4,i), plt.imshow(imread(imfile)), plt.axis('off'), plt.title('epoch = {}'.format(i), size=20)
	i += 1
plt.suptitle('Images generated by VAE after different training epochs', size=25)
plt.savefig('vae_gen.png')